'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='protrainer.local.v1';
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const TODAY=iso(new Date()), date=s=>new Date(`${s}T12:00:00`), addDays=(s,n)=>{const d=date(s);d.setDate(d.getDate()+n);return iso(d)};
const month=s=>s.slice(0,7), uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',users:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M19 8a4 4 0 0 1 0 8 M22 21v-2a4 4 0 0 0-3-3 M13 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0',calendar:'M4 5h16v16H4z M8 3v4 M16 3v4 M4 10h16 M8 14h2 M14 14h2 M8 18h2',dumbbell:'m6 6 12 12 M4 3 3 4l4 4 1-1z M3 7l-1 1 4 4 1-1 M16 16l1-1 4 4-1 1z M17 13l1-1 4 4-1 1',wallet:'M3 5h16v4 M3 5v15h18V9H3 M16 12h5v5h-5z',chart:'M3 3v18h18 M7 15l4-5 4 2 6-8',settings:'M12 8a4 4 0 1 1 0 8 4 4 0 0 1 0-8 M9 3h6l1 3 3 1 2 4-2 3v3l-4 3-3-1-3 1-4-3v-3l-2-3 2-4 3-1z',search:'M15 15l6 6 M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0',bell:'M18 8a6 6 0 0 0-12 0c0 7-3 8-3 8h18s-3-1-3-8 M10 20h4',plus:'M12 4v16 M4 12h16',arrow:'M5 12h14 M14 7l5 5-5 5',up:'M5 19 19 5 M5 5h14v14',close:'m6 6 12 12 M6 18 18 6',check:'m4 12 5 5L20 6',chevron:'m9 5 7 7-7 7',download:'M12 3v12 M6 10l6 6 6-6 M4 17v4h16v-4',clock:'M12 7v5l3 2 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',heart:'M12 21C-5 10 4-2 12 6c8-8 17 4 0 15',edit:'m4 16 12-12 4 4L8 20H4z M14 6l4 4'};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[n]||paths.arrow}"/></svg>`;
const colors=['lime','blue','pink','purple'];
const initials=n=>String(n).trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const clientPhotos={c1:'assets/client-valentina.png',c3:'assets/client-sofia.png',c5:'assets/client-daniela.png'};
const avatar=(c,cls='')=>`<span class="avatar ${colors[(c?.tone||0)%4]} ${cls}">${clientPhotos[c?.id]?`<img src="${clientPhotos[c.id]}" alt="${esc(c?.name)}" loading="lazy">`:esc(initials(c?.name||'PT'))}</span>`;
function demoData(){
 const names=['Valentina Ríos','Carlos Mendoza','Sofía Martínez','Andrés Pérez','Daniela Ruiz','Mateo García'];
 const goals=['Fuerza y definición','Ganar masa muscular','Movilidad y bienestar','Preparación deportiva','Recomposición corporal','Fuerza y resistencia'];
 const routines=[{id:'r1',name:'Full body / Strength',category:'Fuerza',level:'Intermedio',duration:55,notes:'Ajusta la carga según técnica y esfuerzo percibido.',exercises:[{name:'Sentadilla',sets:4,reps:'8–10',rest:90},{name:'Press de banca',sets:3,reps:'10–12',rest:90},{name:'Remo con mancuerna',sets:3,reps:'12',rest:60},{name:'Plancha',sets:3,reps:'40 s',rest:45}]},{id:'r2',name:'Lower body / Build',category:'Hipertrofia',level:'Intermedio',duration:50,notes:'Registrar cargas al terminar la sesión.',exercises:[{name:'Peso muerto rumano',sets:4,reps:'8',rest:120},{name:'Zancadas',sets:3,reps:'12',rest:75},{name:'Hip thrust',sets:4,reps:'10',rest:90}]},{id:'r3',name:'Move / Feel good',category:'Movilidad',level:'Inicial',duration:35,notes:'Movimientos cómodos y controlados.',exercises:[{name:'Movilidad de cadera',sets:3,reps:'8 por lado',rest:30},{name:'Puente de glúteos',sets:3,reps:'15',rest:45},{name:'Bird dog',sets:3,reps:'10 por lado',rest:30}]}];
 const clients=names.map((name,i)=>({id:`c${i+1}`,name,email:`cliente${i+1}@ejemplo.com`,phone:'',birth:'',goal:goals[i],plan:i%2?'Premium':'Personal',fee:i%2?120:80,weight:58+i*5,height:162+i*3,routine:routines[i%3].id,notes:'Ficha de ejemplo. Sustituye estos datos por los de tu cliente.',tone:i,archived:false,joined:addDays(TODAY,-45-i*3)}));
 const payments=clients.map((c,i)=>({id:`p${i+1}`,client:c.id,amount:c.fee,due:addDays(TODAY,i<2?-2:i-2),paid:i>=2&&i<5,paidDate:i>=2&&i<5?addDays(TODAY,-i):'',method:'Transferencia',note:'Mensualidad — datos de ejemplo'}));
 const sessions=[...clients.slice(0,4).map((c,i)=>({id:`s${i+1}`,client:c.id,title:i%2?'Sesión de fuerza':'Entrenamiento personal',date:TODAY,time:`${String(8+i*2).padStart(2,'0')}:00`,duration:60,status:i===0?'Completada':'Programada',routine:c.routine,notes:''})),...clients.slice(0,3).map((c,i)=>({id:`s${i+5}`,client:c.id,title:'Entrenamiento personal',date:addDays(TODAY,i+1),time:'09:00',duration:60,status:'Programada',routine:c.routine,notes:''})),...clients.map((c,i)=>({id:`s${i+8}`,client:c.id,title:'Sesión de fuerza',date:addDays(TODAY,-i-1),time:'10:00',duration:50,status:'Completada',routine:c.routine,notes:''}))];
 const measurements=clients.flatMap((c,i)=>[30,20,10,0].map((ago,j)=>({id:`m${i}-${j}`,client:c.id,date:addDays(TODAY,-ago),weight:c.weight+1.5-j*.5,waist:76+i*2-j*.5,fat:22-i*.4-j*.2,note:'Medición de ejemplo'})));
 return {version:1,profile:{name:'Alex Torres',currency:'USD',specialty:'Entrenamiento personal'},clients,routines,payments,sessions,measurements,demo:true};
}
let storageAvailable=true,data;
try{const stored=localStorage.getItem(KEY);data=stored?JSON.parse(stored):demoData();if(!validData(data))throw Error('Respaldo inválido');}catch{data=demoData();storageAvailable=false;}
function validData(x){return !!x&&x.version===1&&x.profile&&typeof x.profile.name==='string'&&['clients','routines','payments','sessions','measurements'].every(k=>Array.isArray(x[k])&&x[k].length<10000)&&x.clients.every(c=>typeof c.id==='string'&&typeof c.name==='string')&&x.routines.every(r=>typeof r.name==='string'&&Array.isArray(r.exercises))&&x.payments.every(p=>typeof p.id==='string'&&Number.isFinite(Number(p.amount)))&&x.sessions.every(s=>typeof s.date==='string')&&x.measurements.every(m=>Number.isFinite(Number(m.weight)));}
const state={view:'inicio',query:'',clientFilter:'activos',paymentFilter:'todos',calendarDate:TODAY,calendarMonth:month(TODAY),progressClient:data.clients.find(c=>!c.archived)?.id||'',expenseMonth:month(TODAY)};
const activeClients=()=>data.clients.filter(c=>!c.archived), client=id=>data.clients.find(c=>c.id===id)||{id,name:'Cliente archivado',tone:0}, routine=id=>data.routines.find(r=>r.id===id), money=n=>new Intl.NumberFormat('es',{style:'currency',currency:['USD','EUR','VES'].includes(data.profile.currency)?data.profile.currency:'USD',maximumFractionDigits:0}).format(Number(n)||0);
const longDate=(s,opts={day:'numeric',month:'long'})=>date(s).toLocaleDateString('es',opts);
const paidStatus=p=>p.paid?'Pagado':p.due<TODAY?'Vencido':'Pendiente';
const stats=()=>({active:activeClients().length,monthIncome:data.payments.filter(p=>p.paid&&month(p.paidDate||p.due)===month(TODAY)).reduce((n,p)=>n+Number(p.amount),0),pending:data.payments.filter(p=>!p.paid).reduce((n,p)=>n+Number(p.amount),0),todaySessions:data.sessions.filter(s=>s.date===TODAY&&s.status!=='Cancelada'),late:data.payments.filter(p=>!p.paid&&p.due<TODAY).length});
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
function save(){try{localStorage.setItem(KEY,JSON.stringify(data));storageAvailable=true;}catch{storageAvailable=false;toast('No se pudo guardar: exporta un respaldo antes de cerrar.')}updateShell()}
function updateShell(){
 $('#coachName').textContent=data.profile.name;$('#coachAvatar').textContent=initials(data.profile.name);$('#headerAvatar').textContent=initials(data.profile.name);
 $('.local-status').innerHTML=`<i></i>${storageAvailable?'Guardado local':'Sin guardado persistente'}`;$('.demo').textContent=data.demo?'DEMO LOCAL':'ESPACIO LOCAL';
 const nav=[['inicio','Visión general','grid'],['clientes','Clientes','users'],['calendario','Calendario','calendar'],['rutinas','Rutinas','dumbbell'],['pagos','Pagos','wallet'],['progreso','Progreso','chart']];
 $('#nav').innerHTML=nav.map(([v,t,ic])=>`<button class="nav-button ${state.view===v?'active':''}" data-view="${v}" title="${t}" ${state.view===v?'aria-current="page"':''}>${icon(ic)}<span>${t}</span>${v==='clientes'?`<span class="nav-count">${activeClients().length}</span>`:''}</button>`).join('');$('#pageLabel').textContent=[...nav,['ajustes','Ajustes y respaldos']].find(n=>n[0]===state.view)?.[1]||'Visión general';
 $$('[data-icon]').forEach(n=>n.innerHTML=icon(n.dataset.icon));
}
function pageHead(k,title,sub,actions=''){return `<div class="page-head"><div><span class="eyebrow">${k}</span><h1>${title}</h1><p>${sub}</p></div><div class="head-actions">${actions}</div></div>`}
function btn(text,action,cls='primary',extra=''){return `<button class="button ${cls}" data-action="${action}" ${extra}>${icon(action.includes('new')?'plus':'arrow')}${text}</button>`}
function progressFor(id){const sess=data.sessions.filter(s=>s.client===id&&s.date<=TODAY&&s.status!=='Cancelada');return sess.length?Math.round(sess.filter(s=>s.status==='Completada').length/sess.length*100):0}
function stat(label,value,note,ic){return `<div class="stat"><div class="stat-top">${label}${icon(ic)}</div><div class="stat-bottom"><b>${value}</b><small>${note}</small></div></div>`}
function lineChart(values,cls='metric-chart'){if(!values.length)return '<div class="empty-state">Añade mediciones para ver la evolución.</div>';const max=Math.max(...values),min=Math.min(...values),range=Math.max(max-min,1),pts=values.map((v,i)=>`${15+i*(330/Math.max(values.length-1,1))},${130-(v-min)*100/range}`).join(' ');return `<svg class="${cls}" viewBox="0 0 360 160" role="img" aria-label="Gráfico: ${values.map(v=>esc(v)).join(', ')}"><defs><linearGradient id="area"><stop stop-color="#c5ff30" stop-opacity=".8"/><stop offset="1" stop-color="#c5ff30" stop-opacity="0"/></linearGradient></defs><path d="M15 45H345 M15 90H345 M15 130H345" stroke="#e6ecdf" stroke-dasharray="3 4"/><polygon points="15,150 ${pts} ${values.length>1?345:15},150" fill="url(#area)"/><polyline points="${pts}" fill="none" stroke="#9fda18" stroke-width="3" stroke-linejoin="round"/>${values.map((v,i)=>`<circle cx="${15+i*330/Math.max(values.length-1,1)}" cy="${130-(v-min)*100/range}" r="4" fill="#202a17"><title>${v}</title></circle>`).join('')}</svg>`}
function weekStrip(selected){const d=date(selected),monday=addDays(selected,-((d.getDay()+6)%7));return `<div class="calendar-week">${Array.from({length:7},(_,i)=>{const day=addDays(monday,i),has=data.sessions.some(s=>s.date===day)||data.payments.some(p=>p.due===day);return `<button class="day-pill ${day===selected?'selected':''} ${has?'has-event':''}" data-action="select-day" data-date="${day}" aria-label="Ver ${longDate(day)}" aria-pressed="${day===selected}"><span>${date(day).toLocaleDateString('es',{weekday:'short'}).slice(0,3)}</span><strong>${date(day).getDate()}</strong></button>`}).join('')}</div>`}
function agenda(day,limit=99){const events=[...data.sessions.filter(s=>s.date===day&&s.status!=='Cancelada').map(s=>({...s,kind:'session'})),...data.payments.filter(p=>p.due===day&&!p.paid).map(p=>({...p,kind:'payment',time:'Pago',title:'Vence mensualidad'}))].sort((a,b)=>a.time.localeCompare(b.time));return events.length?events.slice(0,limit).map(e=>`<div class="agenda-item"><span class="agenda-time">${esc(e.time)}</span><span class="agenda-marker"></span><div><b>${esc(client(e.client).name)}</b><small>${esc(e.title)} · ${e.kind==='payment'?money(e.amount):`${e.duration} min · ${e.status}`}</small></div><button class="icon-button" data-action="${e.kind==='payment'?'edit-payment':'edit-session'}" data-id="${e.id}" aria-label="Ver ${e.kind==='payment'?'pago':'sesión'} de ${esc(client(e.client).name)}">${icon('chevron')}</button></div>`).join(''):'<div class="empty-state">Un poco de espacio libre.<br>Programa una sesión o un próximo pago.</div>'}
function dashboard(){const s=stats(),name=data.profile.name.split(' ')[0],done=data.sessions.filter(e=>e.status==='Completada').length,total=data.sessions.filter(e=>e.status!=='Cancelada'&&e.date<=TODAY).length;return pageHead('TU DÍA. TU EQUIPO. TU IMPACTO.',`Vamos por más, ${esc(name)}<span style="color:var(--lime)">.</span>`,`${longDate(TODAY,{weekday:'long',day:'numeric',month:'long',year:'numeric'})} · Todo tu entrenamiento, en un solo lugar.`,btn('Nueva sesión','new-session','')+btn('Añadir cliente','new-client'))+
 `<div class="hero-grid"><section class="hero"><span class="eyebrow">COACH BETTER / EVERY DAY</span><span class="mini-label">PROTRAINER CLUB ↗</span><h2>EL SIGUIENTE NIVEL<br>EMPIEZA CONTIGO.</h2><p>Menos tareas pendientes.<br>Más tiempo para transformar vidas.</p><button class="button dark" data-view="rutinas">Crear el próximo reto ${icon('up')}</button><img src="athlete.svg" alt="Ilustración de un atleta entrenando con una mancuerna"></section><section class="card finance"><div class="card-head" style="margin-bottom:0"><span class="eyebrow">INGRESOS DEL MES</span><button class="icon-button" style="border-color:#e0e5d9;width:32px;height:32px" data-view="pagos" aria-label="Ver ingresos y pagos">${icon('up')}</button></div><div class="amount">${money(s.monthIncome)}<small>${esc(data.profile.currency)}</small></div><p>Cobros registrados · ${longDate(TODAY,{month:'long'})}</p><div class="finance-bottom"><div><span class="pill green">${data.payments.filter(p=>p.paid&&month(p.paidDate||p.due)===month(TODAY)).length} cobros recibidos</span><p>${money(s.pending)} por cobrar</p></div>${lineChart([0,...data.payments.filter(p=>p.paid&&month(p.paidDate||p.due)===month(TODAY)).map((p,i,a)=>a.slice(0,i+1).reduce((v,x)=>v+Number(x.amount),0))],'spark')}</div></section></div>
 <div class="stats-row">${stat('Clientes activos',s.active,'Tu equipo','users')}${stat('Sesiones de hoy',s.todaySessions.length,`${s.todaySessions.filter(x=>x.status==='Completada').length} completadas`,'calendar')}${stat('Sesiones completadas',total?`${Math.round(done/total*100)}%`:'—',`${done} en total`,'chart')}${stat('Pagos vencidos',s.late,s.late?'Revisar cobros':'Todo al día','wallet')}</div>
 <div class="main-grid"><section><div class="section-heading"><h2>Tu equipo en movimiento</h2><button data-view="clientes">Todos los clientes ↗</button></div><div class="card">${activeClients().slice(0,4).map(c=>`<div class="client-row">${avatar(c)}<div class="client-info"><b>${esc(c.name)}</b><p>${esc(c.goal)}</p></div><div><span style="display:block;text-align:right;font-size:11px;margin-bottom:7px">${progressFor(c.id)}% <span style="color:#9ca998">asistencia</span></span><div class="progress-bar"><span style="width:${progressFor(c.id)}%"></span></div></div><button class="table-open" data-action="client-detail" data-id="${c.id}" aria-label="Abrir ficha de ${esc(c.name)}">↗</button></div>`).join('')||'<div class="empty-state">Añade tu primer cliente.</div>'}</div></section><section><div class="section-heading"><h2>Tu agenda</h2><button data-view="calendario">Abrir calendario ↗</button></div><div class="card white">${weekStrip(state.calendarDate)}<div class="calendar-subhead"><span>${state.calendarDate===TODAY?'HOY':longDate(state.calendarDate).toUpperCase()}</span><span>SESIONES & PAGOS</span></div>${agenda(state.calendarDate,3)}</div></section></div>
 <div class="bottom-grid"><section class="card white"><div class="card-head"><h3>Una semana de movimiento</h3><span class="pill green">SESIONES</span></div><div class="bar-chart">${Array.from({length:7},(_,i)=>{const day=addDays(TODAY,i-6),n=data.sessions.filter(s=>s.date===day&&s.status==='Completada').length;return `<div class="bar-col"><div class="bar ${i===6?'highlight':''}" style="height:${Math.min(72,8+n*23)}px" title="${n} sesiones completadas"></div><span>${date(day).toLocaleDateString('es',{weekday:'short'}).slice(0,3)} · ${n}</span></div>`}).join('')}</div></section><section class="card"><div class="routine-mini"><div class="routine-art">${icon('dumbbell')}</div><div><span class="eyebrow">TU PRÓXIMA GRAN SESIÓN</span><h3>${esc(data.routines[0]?.name||'Diseña tu primera rutina')}</h3><p>${data.routines[0]?.exercises.length||0} ejercicios · ${data.routines[0]?.duration||0} min · A tu manera</p><button class="button small" data-view="rutinas">Explorar rutinas ${icon('arrow')}</button></div></div></section></div>`}
function clientCards(){return data.clients.filter(c=>(state.clientFilter==='todos'||state.clientFilter==='archivo'?state.clientFilter==='todos'||c.archived:!c.archived)&&`${c.name} ${c.goal} ${c.email}`.toLowerCase().includes(state.query.toLowerCase())).map(c=>`<article class="client-card"><div class="client-card-top">${avatar(c)}<span class="pill ${c.archived?'orange':'green'}">${c.archived?'Archivado':esc(c.plan)}</span></div><h3>${esc(c.name)}</h3><p class="subtle">${esc(c.goal)}</p><div style="display:flex;justify-content:space-between;font-size:11px;margin-bottom:8px"><span>Asistencia registrada</span><b>${progressFor(c.id)}%</b></div><div class="progress-bar"><span style="width:${progressFor(c.id)}%"></span></div><div class="client-card-bottom"><span>${money(c.fee)} <small>/ mes</small></span><button class="button light small" data-action="client-detail" data-id="${c.id}">Ver ficha ${icon('up')}</button></div></article>`).join('')||'<div class="card white empty-state">No encontramos clientes. Añade uno o cambia la búsqueda.</div>'}
function clientsPage(){return pageHead('PERSONAS ANTES QUE NÚMEROS.','Tu equipo<span style="color:var(--lime)">.</span>','Fichas, objetivos, rutinas y evolución de cada cliente.',btn('Añadir cliente','new-client'))+`<div class="toolbar"><div class="search-field">${icon('search')}<input id="clientSearch" aria-label="Buscar clientes" placeholder="Buscar por nombre u objetivo…" value="${esc(state.query)}"></div><div class="filter-tabs">${[['activos','Activos'],['todos','Todos'],['archivo','Archivo']].map(([v,t])=>`<button data-action="client-filter" data-filter="${v}" class="${state.clientFilter===v?'active':''}">${t}</button>`).join('')}</div></div><div class="client-grid" id="clientGrid">${clientCards()}</div>`}
function monthCalendar(){const first=date(state.calendarMonth+'-01'),offset=(first.getDay()+6)%7;const days=new Date(first.getFullYear(),first.getMonth()+1,0).getDate();return `<div class="calendar-month">${['LUN','MAR','MIÉ','JUE','VIE','SÁB','DOM'].map(x=>`<div class="weekday">${x}</div>`).join('')}${Array.from({length:Math.ceil((offset+days)/7)*7},(_,i)=>{const n=i-offset+1;if(n<1||n>days)return '<div class="month-cell empty" aria-hidden="true"></div>';const day=state.calendarMonth+'-'+String(n).padStart(2,'0'),ses=data.sessions.filter(s=>s.date===day&&s.status!=='Cancelada'),pay=data.payments.filter(p=>p.due===day&&!p.paid);return `<button class="month-cell ${day===TODAY?'today':''} ${day===state.calendarDate?'selected':''}" data-action="select-day" data-date="${day}" aria-label="${longDate(day)}: ${ses.length} sesiones y ${pay.length} pagos"><strong>${n}</strong>${ses.slice(0,2).map(s=>`<span class="cal-event">${esc(s.time)} <span class="event-name">${esc(client(s.client).name.split(' ')[0])}</span></span>`).join('')}${pay.length?`<span class="cal-event payment">${money(pay.reduce((n,p)=>n+Number(p.amount),0))}</span>`:''}${ses.length>2?`<span class="month-mobile">+${ses.length-2}</span>`:''}</button>`}).join('')}</div>`}
function calendarPage(){return pageHead('CADA DÍA CUENTA.','Tu calendario<span style="color:var(--lime)">.</span>','Entrenamientos y vencimientos, sin perder nada de vista.',btn('Registrar pago','new-payment','')+btn('Nueva sesión','new-session'))+`<div class="calendar-layout"><div class="card white"><div class="card-head"><h2 class="calendar-title">${longDate(state.calendarMonth+'-01',{month:'long',year:'numeric'})}</h2><div class="calendar-controls"><button class="icon-button" data-action="month-prev" aria-label="Mes anterior">‹</button><button class="button light small" data-action="month-today">Hoy</button><button class="icon-button" data-action="month-next" aria-label="Mes siguiente">›</button></div></div>${monthCalendar()}<p class="form-hint" style="margin-top:15px">Verde claro: sesiones · Oscuro: pagos por vencer. Selecciona un día para ver el detalle.</p></div><div class="card white"><span class="eyebrow" style="color:#687d58">${longDate(state.calendarDate,{weekday:'long'}).toUpperCase()}</span><h2>${longDate(state.calendarDate)}</h2><div style="margin-top:18px">${agenda(state.calendarDate)}</div><button class="button dark" style="margin-top:18px;width:100%" data-action="new-session" data-date="${state.calendarDate}">${icon('plus')}Agendar aquí</button></div></div>`}
function paymentsPage(){const s=stats();let items=data.payments.filter(p=>month(p.due)===state.expenseMonth&&(state.paymentFilter==='todos'||paidStatus(p).toLowerCase()===state.paymentFilter));items.sort((a,b)=>a.due.localeCompare(b.due));return pageHead('ORDEN EN TUS COBROS.','Cada esfuerzo cuenta<span style="color:var(--lime)">.</span>','Mensualidades, vencimientos y pagos registrados.',btn('Registrar pago','new-payment'))+`<div class="stats-row">${stat('Cobrado este mes',money(s.monthIncome),'Recibido','wallet')}${stat('Por cobrar',money(s.pending),'Todos los meses','clock')}${stat('Pagos vencidos',s.late,'Revisar fechas','calendar')}${stat('Clientes activos',s.active,'Planes activos','users')}</div><div class="toolbar"><div class="filter-tabs">${[['todos','Todos'],['pendiente','Pendientes'],['pagado','Pagados'],['vencido','Vencidos']].map(([v,t])=>`<button data-action="payment-filter" data-filter="${v}" class="${state.paymentFilter===v?'active':''}">${t}</button>`).join('')}</div><label style="margin:0;color:#b8c4b1">Mes de vencimiento <input id="paymentMonth" type="month" aria-label="Mes de vencimiento" value="${state.expenseMonth}" style="width:175px;margin-left:8px"></label></div><div class="card white table-wrap"><table><thead><tr><th>CLIENTE</th><th>IMPORTE</th><th>VENCIMIENTO</th><th>ESTADO</th><th>ACCIONES</th></tr></thead><tbody>${items.map(p=>`<tr><td><div class="table-person">${avatar(client(p.client))}<span>${esc(client(p.client).name)}</span></div></td><td class="amount-cell">${money(p.amount)}</td><td>${longDate(p.due)}</td><td><span class="pill ${p.paid?'green':'orange'}">${paidStatus(p)}</span></td><td>${!p.paid?`<button class="button dark small" data-action="receive-payment" data-id="${p.id}">Registrar recibido</button>`:''}<button class="table-open" data-action="edit-payment" data-id="${p.id}" aria-label="Editar pago de ${esc(client(p.client).name)}">↗</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty-state">No hay pagos con este filtro.</td></tr>'}</tbody></table></div><p class="subtle" style="margin-top:15px">Este registro lleva el control de cobros; no procesa transferencias ni cargos bancarios.</p>`}
function routinesPage(){return pageHead('PROGRAMAR. ADAPTAR. EVOLUCIONAR.','Rutinas con intención<span style="color:var(--lime)">.</span>','Construye sesiones y asigna el plan adecuado a cada persona.',btn('Crear rutina','new-routine'))+`<div class="routine-grid">${data.routines.map((r,i)=>`<article class="routine-card ${i%3===1?'white':''}"><div class="routine-art">${icon('dumbbell')}</div><span class="eyebrow">${esc(r.category)} / ${esc(r.level)}</span><h3>${esc(r.name)}</h3><p>${r.duration} minutos · ${r.exercises.length} ejercicios · ${data.clients.filter(c=>c.routine===r.id&&!c.archived).length} clientes asignados</p><ol>${r.exercises.slice(0,4).map(e=>`<li>${esc(e.name)} <span style="opacity:.6">/ ${esc(e.sets)} × ${esc(e.reps)}</span></li>`).join('')}</ol><button class="button ${i%3===1?'dark':'primary'} small" data-action="edit-routine" data-id="${r.id}">Editar rutina ${icon('edit')}</button><button class="button ${i%3===1?'light':''} small" data-action="assign-routine" data-id="${r.id}">Asignar a cliente ${icon('arrow')}</button></article>`).join('')||'<div class="card empty-state">Crea tu primera rutina para empezar.</div>'}</div>`}
function progressPage(){const c=client(state.progressClient),ms=data.measurements.filter(m=>m.client===c.id).sort((a,b)=>a.date.localeCompare(b.date)),last=ms.at(-1),first=ms[0];return pageHead('PROGRESO MÁS ALLÁ DEL PESO.','Pequeños pasos. Grandes cambios<span style="color:var(--lime)">.</span>','Mediciones y observaciones para seguir cada proceso.',btn('Añadir medición','new-measurement'))+`<div class="toolbar"><label style="color:#b9c4b3;margin:0">Cliente <select id="progressSelect" style="width:260px;margin-left:10px">${activeClients().map(x=>`<option value="${x.id}" ${x.id===c.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><span class="subtle">${ms.length} mediciones registradas</span></div><div class="main-grid"><section class="card white"><div class="card-head"><div><span class="eyebrow" style="color:#687b59">EVOLUCIÓN DEL PESO</span><h2>${last?`${last.weight} kg`:'Sin mediciones'}</h2></div><span class="pill green">${last&&first?`${(last.weight-first.weight).toFixed(1)} kg desde inicio`:'Punto de partida'}</span></div>${lineChart(ms.map(m=>Number(m.weight)))}<div class="metric-labels"><span>${ms.length?longDate(ms[0].date):'Inicio'}</span><span>${ms.length?longDate(ms.at(-1).date):'Hoy'}</span></div><div class="mini-summary"><div>Cintura<b>${last?.waist?`${last.waist} cm`:'—'}</b></div><div>Grasa corporal<b>${last?.fat?`${last.fat}%`:'—'}</b></div><div>Asistencia<b>${progressFor(c.id)}%</b></div></div><span class="chart-legend"><i></i>Peso registrado · kg</span></section><section class="card"><div class="detail-title">${avatar(c)}<div><h2>${esc(c.name)}</h2><p class="subtle" style="margin-top:5px">${esc(c.goal)}</p></div></div><span class="eyebrow">OBSERVACIONES DEL ENTRENADOR</span><p class="notes">${esc(c.notes||'Añade observaciones en la ficha del cliente.')}</p><div style="margin-top:24px"><span class="eyebrow">RUTINA ASIGNADA</span><h3>${esc(routine(c.routine)?.name||'Sin rutina asignada')}</h3></div><button class="button small" style="margin-top:24px" data-action="client-detail" data-id="${c.id}">Abrir ficha ${icon('arrow')}</button></section></div><div class="card white table-wrap" style="margin-top:20px"><div class="card-head"><h3>Historial de mediciones</h3></div><table><thead><tr><th>FECHA</th><th>PESO</th><th>CINTURA</th><th>GRASA</th><th>OBSERVACIÓN</th></tr></thead><tbody>${[...ms].reverse().map(m=>`<tr><td>${longDate(m.date)}</td><td>${m.weight} kg</td><td>${m.waist?`${m.waist} cm`:'—'}</td><td>${m.fat?`${m.fat}%`:'—'}</td><td>${esc(m.note)}</td></tr>`).join('')||'<tr><td colspan="5" class="empty-state">Todavía no hay mediciones.</td></tr>'}</tbody></table></div>`}
function settingsPage(){return pageHead('TU ESPACIO, A TU MANERA.','Ajustes y respaldos<span style="color:var(--lime)">.</span>','Personaliza tu perfil y conserva una copia de tus registros.')+`<div class="settings-grid"><section class="card white"><h3>Perfil del entrenador</h3><form id="profileForm"><div class="form-grid"><div class="full"><label for="coachInput">Nombre del entrenador</label><input id="coachInput" name="name" value="${esc(data.profile.name)}" required maxlength="80"></div><div class="full"><label for="specialtyInput">Especialidad</label><input id="specialtyInput" name="specialty" value="${esc(data.profile.specialty)}" maxlength="120"></div><div><label for="currencyInput">Moneda</label><select id="currencyInput" name="currency">${['USD','EUR','VES'].map(x=>`<option ${x===data.profile.currency?'selected':''}>${x}</option>`).join('')}</select></div></div><div class="form-foot"><button class="button dark" type="submit">Guardar perfil ${icon('check')}</button></div></form></section><section class="card white"><h3>Tus datos, bajo tu control</h3><p>Los registros se guardan en este navegador. Exporta un respaldo para conservarlos o llevarlos a otro equipo.</p><div class="backup-actions">${btn('Exportar respaldo JSON','export-backup','dark')}${btn('Importar respaldo','import-backup','light')}${btn('Exportar clientes CSV','export-clients','light')}</div><div class="alert-info">Aplicación local para un entrenador. Sin servidor, cuentas ni sincronización entre dispositivos. Los datos de ejemplo son ficticios. Guarda los respaldos en un lugar privado.</div><button class="button light" style="margin-top:20px" data-action="start-empty">Empezar sin datos de ejemplo</button></section></div>`}
function render(){updateShell();$('#content').innerHTML=({inicio:dashboard,clientes:clientsPage,calendario:calendarPage,pagos:paymentsPage,rutinas:routinesPage,progreso:progressPage,ajustes:settingsPage}[state.view]||dashboard)();}
function go(view){if(!['inicio','clientes','calendario','pagos','rutinas','progreso','ajustes'].includes(view))view='inicio';state.view=view;if(location.hash.slice(1)!==view)location.hash=view;render();window.scrollTo({top:0,behavior:'instant'});}
const optionsClients=id=>activeClients().map(c=>`<option value="${c.id}" ${c.id===id?'selected':''}>${esc(c.name)}</option>`).join('');
const optionsRoutines=id=>'<option value="">Sin asignar</option>'+data.routines.map(r=>`<option value="${r.id}" ${r.id===id?'selected':''}>${esc(r.name)}</option>`).join('');
function field(name,label,value='',type='text',extra=''){return `<div><label for="f-${name}">${label}</label><input id="f-${name}" name="${name}" type="${type}" value="${esc(value)}" ${extra}></div>`}
function select(name,label,options){return `<div><label for="f-${name}">${label}</label><select id="f-${name}" name="${name}">${options}</select></div>`}
const textField=(name,label,value='')=>`<div class="full"><label for="f-${name}">${label}</label><textarea id="f-${name}" name="${name}" maxlength="3000">${esc(value)}</textarea></div>`;
function formWrap(kind,id,body,extra=''){return `<form id="entityForm" data-kind="${kind}" data-id="${id||''}"><div class="form-grid">${body}</div><div id="formError" class="form-error" role="alert"></div><div class="form-foot">${extra}<button class="button light" type="button" data-action="close-modal">Cancelar</button><button class="button dark" type="submit">Guardar ${icon('check')}</button></div></form>`}
function modal(title,html){$('#dialogTitle').textContent=title;$('#dialogBody').innerHTML=html;if(!$('#modal').open)$('#modal').showModal();}
function editClient(id){const c=data.clients.find(c=>c.id===id)||{};modal(c.id?'Editar cliente':'Añadir cliente',formWrap('client',c.id,field('name','Nombre completo',c.name,'text','required maxlength="80"')+field('email','Correo electrónico',c.email,'email','maxlength="120"')+field('phone','Teléfono',c.phone,'tel','maxlength="40"')+field('birth','Fecha de nacimiento',c.birth,'date',`max="${TODAY}"`)+field('goal','Objetivo principal',c.goal,'text','required maxlength="150"')+select('plan','Plan',['Personal','Premium','Online'].map(p=>`<option ${p===c.plan?'selected':''}>${p}</option>`).join(''))+field('fee','Mensualidad',c.fee||80,'number','min="0" max="100000" step="0.01" required')+select('routine','Rutina asignada',optionsRoutines(c.routine))+field('weight','Peso inicial / actual (kg)',c.weight,'number','min="20" max="400" step="0.1"')+field('height','Estatura (cm)',c.height,'number','min="80" max="250"')+textField('notes','Observaciones, limitaciones y preferencias',c.notes)));}
function detailClient(id){const c=client(id),r=routine(c.routine),ms=data.measurements.filter(m=>m.client===id).sort((a,b)=>a.date.localeCompare(b.date)),pending=data.payments.filter(p=>p.client===id&&!p.paid).reduce((v,p)=>v+Number(p.amount),0);modal('Ficha del cliente',`<div class="detail-title">${avatar(c)}<div><h2>${esc(c.name)}</h2><p class="form-hint">${esc(c.goal)}</p></div></div><div class="detail-grid"><section><div class="info-list"><div><span>Plan</span><b>${esc(c.plan)} / ${money(c.fee)}</b></div><div><span>Email</span><b>${esc(c.email||'No registrado')}</b></div><div><span>Teléfono</span><b>${esc(c.phone||'No registrado')}</b></div><div><span>Nacimiento</span><b>${c.birth?longDate(c.birth,{day:'numeric',month:'short',year:'numeric'}):'No registrado'}</b></div><div><span>Estatura</span><b>${c.height?`${c.height} cm`:'—'}</b></div><div><span>Rutina</span><b>${esc(r?.name||'Sin asignar')}</b></div></div></section><section style="background:#f2f6eb;padding:17px;border-radius:17px"><div class="info-list"><div><span>Último peso</span><b>${ms.at(-1)?.weight||c.weight||'—'} kg</b></div><div><span>Asistencia</span><b>${progressFor(id)}%</b></div><div><span>Saldo pendiente</span><b>${money(pending)}</b></div></div></section></div><h3 style="margin:25px 0 10px">Observaciones</h3><p class="notes">${esc(c.notes||'Sin observaciones.')}</p><div class="form-foot"><button class="button light" data-action="toggle-archive" data-id="${c.id}">${c.archived?'Restaurar cliente':'Archivar cliente'}</button><button class="button light" data-action="client-progress" data-id="${c.id}">Ver progreso</button><button class="button dark" data-action="edit-client" data-id="${c.id}">Editar ficha ${icon('edit')}</button></div>`)}
function editSession(id,day){if(!activeClients().length)return toast('Añade un cliente antes de programar sesiones.');const s=data.sessions.find(s=>s.id===id)||{};modal(s.id?'Detalle de sesión':'Nueva sesión',formWrap('session',s.id,select('client','Cliente',optionsClients(s.client))+field('title','Nombre de la sesión',s.title||'Entrenamiento personal','text','required maxlength="120"')+field('date','Fecha',s.date||day||state.calendarDate,'date','required')+field('time','Hora',s.time||'09:00','time','required')+field('duration','Duración (minutos)',s.duration||60,'number','min="10" max="300" required')+select('status','Estado',['Programada','Completada','Cancelada'].map(x=>`<option ${x===s.status?'selected':''}>${x}</option>`).join(''))+select('routine','Rutina de esta sesión',optionsRoutines(s.routine))+textField('notes','Notas de la sesión: cargas, esfuerzo y observaciones',s.notes)));}
function editPayment(id,receive=false){if(!activeClients().length)return toast('Añade un cliente antes de registrar pagos.');const p=data.payments.find(p=>p.id===id)||{};modal(receive?'Registrar cobro recibido':p.id?'Editar pago':'Registrar pago',formWrap('payment',p.id,select('client','Cliente',optionsClients(p.client))+field('amount',`Importe (${data.profile.currency})`,p.amount||activeClients()[0]?.fee||80,'number','min="0.01" max="1000000" step="0.01" required')+field('due','Fecha de vencimiento',p.due||state.calendarDate,'date','required')+select('paid','Estado',`<option value="no" ${!p.paid&&!receive?'selected':''}>Pendiente</option><option value="yes" ${p.paid||receive?'selected':''}>Pagado</option>`)+field('paidDate','Fecha de cobro (si está pagado)',p.paidDate||(receive?TODAY:''),'date')+select('method','Método',['Transferencia','Efectivo','Tarjeta','Otro'].map(x=>`<option ${x===p.method?'selected':''}>${x}</option>`).join(''))+textField('note','Concepto o referencia',p.note||'Mensualidad')));}
function exerciseRow(e={name:'',sets:3,reps:'10–12',rest:60}){return `<div class="exercise-row"><input aria-label="Nombre del ejercicio" class="ex-name" value="${esc(e.name)}" placeholder="Ejercicio" required maxlength="120"><input aria-label="Series" class="ex-sets" type="number" value="${esc(e.sets)}" min="1" max="20" required><input aria-label="Repeticiones" class="ex-reps" value="${esc(e.reps)}" required maxlength="30"><input aria-label="Descanso en segundos" class="ex-rest" type="number" value="${esc(e.rest)}" min="0" max="600" required><button type="button" data-action="remove-exercise" aria-label="Quitar ejercicio">×</button></div>`}
function editRoutine(id){const r=data.routines.find(r=>r.id===id)||{};modal(r.id?'Editar rutina':'Crear rutina',formWrap('routine',r.id,`<div class="full">${field('name','Nombre de la rutina',r.name,'text','required maxlength="100"')}</div>`+select('category','Enfoque',['Fuerza','Hipertrofia','Movilidad','Cardio','Funcional','Mixto'].map(x=>`<option ${x===r.category?'selected':''}>${x}</option>`).join(''))+select('level','Nivel',['Inicial','Intermedio','Avanzado'].map(x=>`<option ${x===r.level?'selected':''}>${x}</option>`).join(''))+field('duration','Duración estimada (minutos)',r.duration||50,'number','min="10" max="300" required')+`<div class="full"><label>Ejercicios</label><div class="exercise-labels"><span>Ejercicio</span><span>Series</span><span>Reps</span><span>Desc. (s)</span></div><div class="exercise-fields" id="exercises">${(r.exercises||[{}]).map(e=>exerciseRow(e.name?e:undefined)).join('')}</div><button class="button light small" type="button" style="margin-top:12px" data-action="add-exercise">${icon('plus')}Añadir ejercicio</button></div>`+textField('notes','Indicaciones del entrenador',r.notes)));}
function measurement(){if(!activeClients().length)return toast('Añade un cliente antes de registrar mediciones.');modal('Añadir medición',formWrap('measurement','',select('client','Cliente',optionsClients(state.progressClient))+field('date','Fecha de medición',TODAY,'date','required')+field('weight','Peso (kg)','','number','min="20" max="400" step="0.1" required')+field('waist','Cintura (cm)','','number','min="20" max="300" step="0.1"')+field('fat','Grasa corporal (%)','','number','min="1" max="70" step="0.1"')+textField('note','Observaciones')));}
function assignRoutine(id){if(!activeClients().length)return toast('Añade un cliente primero.');modal('Asignar rutina',formWrap('assign',id,select('client','Cliente',optionsClients(''))+`<div class="full alert-info">Plan: <b>${esc(routine(id)?.name)}</b>. Se reemplazará la rutina asignada a este cliente; sus sesiones anteriores se conservan.</div>`));}
function download(filename,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);}
function exportData(){download(`ProTrainer-respaldo-${TODAY}.json`,JSON.stringify(data,null,2),'application/json');toast('Respaldo exportado.');}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav){go(nav.dataset.view);return;}const b=e.target.closest('[data-action]');if(!b)return;const {action,id}=b.dataset;
 const actions={'new-client':()=>editClient(),'edit-client':()=>editClient(id),'client-detail':()=>detailClient(id),'new-session':()=>editSession('',b.dataset.date),'edit-session':()=>editSession(id),'new-payment':()=>editPayment(),'edit-payment':()=>editPayment(id),'receive-payment':()=>editPayment(id,true),'new-routine':()=>editRoutine(),'edit-routine':()=>editRoutine(id),'assign-routine':()=>assignRoutine(id),'new-measurement':measurement,'close-modal':()=>$('#modal').close(),'select-day':()=>{state.calendarDate=b.dataset.date;if(state.view==='calendario')state.calendarMonth=month(b.dataset.date);render()},'client-filter':()=>{state.clientFilter=b.dataset.filter;render()},'payment-filter':()=>{state.paymentFilter=b.dataset.filter;render()},'client-progress':()=>{state.progressClient=id;$('#modal').close();go('progreso')},'toggle-archive':()=>{const c=client(id);c.archived=!c.archived;save();$('#modal').close();render();toast(c.archived?'Cliente archivado. Puedes restaurarlo desde Archivo.':'Cliente restaurado.')},'month-prev':()=>changeMonth(-1),'month-next':()=>changeMonth(1),'month-today':()=>{state.calendarMonth=month(TODAY);state.calendarDate=TODAY;render()},'add-exercise':()=>$('#exercises').insertAdjacentHTML('beforeend',exerciseRow()),'remove-exercise':()=>{if($$('.exercise-row').length>1)b.closest('.exercise-row').remove();else toast('La rutina necesita al menos un ejercicio.')},'export-backup':exportData,'import-backup':()=>$('#importFile').click(),'export-clients':()=>{const rows=[['Nombre','Email','Telefono','Objetivo','Plan','Mensualidad','Estado'],...data.clients.map(c=>[c.name,c.email,c.phone,c.goal,c.plan,c.fee,c.archived?'Archivado':'Activo'])];const clean=v=>{const s=String(v??'');return '"'+(/^[=+@-]/.test(s)?"'":'')+s.replaceAll('"','""')+'"'};download(`ProTrainer-clientes-${TODAY}.csv`,'\ufeff'+rows.map(r=>r.map(clean).join(';')).join('\r\n'),'text/csv;charset=utf-8');toast('Lista de clientes exportada.')},'start-empty':()=>modal('Empezar tu espacio',`<p class="notes">Se quitarán los datos de ejemplo de este navegador. Primero descarga un respaldo para conservar cualquier registro que hayas agregado.</p><div class="form-foot"><button class="button light" data-action="export-backup">Descargar respaldo</button><button class="button dark" data-action="confirm-empty">Crear espacio vacío</button></div>`),'confirm-empty':()=>{exportData();data={version:1,profile:data.profile,clients:[],routines:[],sessions:[],payments:[],measurements:[],demo:false};state.progressClient='';save();$('#modal').close();go('clientes');toast('Espacio vacío creado. Se descargó el respaldo anterior.')}};
 actions[action]?.();
});
function changeMonth(n){const d=date(state.calendarMonth+'-01');d.setMonth(d.getMonth()+n);state.calendarMonth=month(iso(d));render();}
document.addEventListener('input',e=>{if(e.target.id==='clientSearch'){state.query=e.target.value;$('#clientGrid').innerHTML=clientCards();}});
document.addEventListener('change',e=>{if(e.target.id==='progressSelect'){state.progressClient=e.target.value;render();}if(e.target.id==='paymentMonth'){if(e.target.value){state.expenseMonth=e.target.value;render();}}});
document.addEventListener('submit',e=>{e.preventDefault();const f=e.target;if(f.id==='profileForm'){const x=Object.fromEntries(new FormData(f));if(!x.name.trim())return toast('Escribe el nombre del entrenador.');data.profile={...data.profile,name:x.name.trim(),specialty:x.specialty.trim(),currency:x.currency};save();render();toast('Perfil actualizado.');return;}if(f.id!=='entityForm')return;const x=Object.fromEntries(new FormData(f)),kind=f.dataset.kind,id=f.dataset.id;
 try{
 if(kind==='client'){if(!x.name.trim()||!x.goal.trim())throw Error('Nombre y objetivo son obligatorios.');const c={...data.clients.find(c=>c.id===id),id:id||uid(),...x,name:x.name.trim(),fee:Number(x.fee),weight:x.weight?Number(x.weight):null,height:x.height?Number(x.height):null,tone:id?client(id).tone:data.clients.length,archived:id?client(id).archived:false,joined:id?client(id).joined:TODAY};upsert('clients',c);if(!state.progressClient)state.progressClient=c.id;}
 if(kind==='session'){if(!x.client||!x.date||!x.time)throw Error('Selecciona cliente, fecha y hora.');const duration=Number(x.duration),start=x.time.split(':').reduce((a,b,i)=>a+Number(b)*(i?1:60),0);const conflict=data.sessions.some(s=>s.id!==id&&s.date===x.date&&s.status!=='Cancelada'&&x.status!=='Cancelada'&&(()=>{const t=s.time.split(':').reduce((a,b,i)=>a+Number(b)*(i?1:60),0);return start<t+Number(s.duration)&&start+duration>t;})());if(conflict)throw Error('Ese horario coincide con otra sesión. Ajusta la hora o la duración.');upsert('sessions',{...x,id:id||uid(),duration});}
 if(kind==='payment'){if(!x.client||!x.due||Number(x.amount)<=0)throw Error('Cliente, importe y fecha son obligatorios.');if(x.paid==='yes'&&!x.paidDate)throw Error('Indica la fecha en la que recibiste el pago.');upsert('payments',{...x,id:id||uid(),amount:Number(x.amount),paid:x.paid==='yes',paidDate:x.paid==='yes'?x.paidDate:''});}
 if(kind==='routine'){const exercises=$$('.exercise-row').map(r=>({name:r.querySelector('.ex-name').value.trim(),sets:Number(r.querySelector('.ex-sets').value),reps:r.querySelector('.ex-reps').value.trim(),rest:Number(r.querySelector('.ex-rest').value)}));if(!x.name.trim()||!exercises.length||exercises.some(e=>!e.name||!e.reps))throw Error('Añade un nombre y completa todos los ejercicios.');upsert('routines',{...x,id:id||uid(),duration:Number(x.duration),exercises});}
 if(kind==='measurement'){if(!x.client||Number(x.weight)<20)throw Error('Selecciona un cliente e indica su peso.');upsert('measurements',{...x,id:uid(),weight:Number(x.weight),waist:x.waist?Number(x.waist):null,fat:x.fat?Number(x.fat):null});state.progressClient=x.client;client(x.client).weight=Number(x.weight);}
 if(kind==='assign'){const c=data.clients.find(c=>c.id===x.client);if(!c)throw Error('Selecciona un cliente.');c.routine=id;}
 save();$('#modal').close();render();toast(kind==='assign'?'Rutina asignada.':'Registro guardado.');
 }catch(err){$('#formError').textContent=err.message;}
});
function upsert(key,item){const idx=data[key].findIndex(x=>x.id===item.id);if(idx<0)data[key].push(item);else data[key][idx]=item;}
$('#importFile').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>8*1024*1024)throw Error('El respaldo supera el tamaño permitido (8 MB).');const candidate=JSON.parse(await file.text());if(!validData(candidate))throw Error('El archivo no es un respaldo válido de ProTrainer.');modal('Importar respaldo',`<p class="notes">Este respaldo contiene ${candidate.clients.length} clientes, ${candidate.sessions.length} sesiones y ${candidate.payments.length} pagos. Reemplazará los registros actuales de este navegador; antes se descargará una copia de seguridad.</p><div class="form-foot"><button class="button light" data-action="close-modal">Cancelar</button><button class="button dark" id="confirmImport">Importar respaldo</button></div>`);$('#confirmImport').onclick=()=>{exportData();data=candidate;state.progressClient=activeClients()[0]?.id||'';save();$('#modal').close();render();toast('Respaldo importado.');};}catch(err){toast(err.message);}e.target.value='';});
$('#closeModal').onclick=()=>$('#modal').close();$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
$('#searchOpen').onclick=()=>{go('clientes');$('#clientSearch')?.focus();};$('#notifications').onclick=()=>{state.paymentFilter='vencido';go('pagos');};
window.addEventListener('hashchange',()=>{const v=location.hash.slice(1);if(v!==state.view)go(v);});
state.view=['inicio','clientes','calendario','pagos','rutinas','progreso','ajustes'].includes(location.hash.slice(1))?location.hash.slice(1):'inicio';render();
if(!storageAvailable)toast('No se pudo recuperar el guardado. Conserva un respaldo de tus datos.');
